import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="pt-br">
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>

      <body className={`${inter.variable} antialiased`}>{children}</body>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
