import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme";
import { QueryProvider } from "@/providers/query";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Duplicati Dashboard",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="pt-br">
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <QueryProvider>
          <body className={`${inter.variable} antialiased`}>{children}</body>
        </QueryProvider>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
